# Python 3 CircleCI 2.0 configuration file
# For Synthego ICE
#
# https://circleci.com/docs/2.0/language-python/
#
version: 2
jobs:
  build:
    working_directory: ~/ice
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run the Tests
          command: |
            . venv/bin/activate
            py.test ice/tests --junitxml=test-reports/output.xml
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
